### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by wallnutkraken** [sushihangover/CursesSharp#11]
Compiling from a fresh copy fails. Info:

```
(~/curse/CursesSharp) >
mdtool build CursesSharp.Native.Linux.sln --target:Clean --configuration:Debug
MonoDevelop Build Tool
Loading solution: /home/gnugat/curse/CursesSharp/CursesSharp.Native.Linux.sln
   Loading solution:
   /home/gnugat/curse/CursesSharp/CursesSharp.Native.Linux.sln
      Loading projects ..
         WARNING: Error while trying to load the project
         '/home/gnugat/curse/CursesSharp/CursesSharp.Native/CursesSharp.Native.L
         inux.cproj': Object reference not set to an instance of an object
Cleaning Solution: CursesSharp.Native.Linux (Debug)
(~/curse/CursesSharp) >
mdtool build CursesSharp.Native.Linux.sln --target:Build --configuration:Debug
MonoDevelop Build Tool
Loading solution: /home/gnugat/curse/CursesSharp/CursesSharp.Native.Linux.sln
   Loading solution:
   /home/gnugat/curse/CursesSharp/CursesSharp.Native.Linux.sln
      Loading projects ..
         WARNING: Error while trying to load the project
         '/home/gnugat/curse/CursesSharp/CursesSharp.Native/CursesSharp.Native.L
         inux.cproj': Object reference not set to an instance of an object
Building Solution: CursesSharp.Native.Linux (Debug)
```

uname -a: 
`Linux TUSKBot 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux`

```
> mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by sushihangover** [comment]
> Loading projects ..
>        WARNING: Error while trying to load the project
>         '/home/gnugat/curse/CursesSharp/CursesSharp.Native/CursesSharp.Native.L
>         inux.cproj': Object reference not set to an instance of an object

Appears to be a MonoDevelop issue(?)... 

1) Which version of MonoDevelop do you have installed?
2) If you load the Solution/Project into MonoDevelop and build it from there do you get the same error? (Also at that point you can look at the MD logs for more details...

FYI: I've only tested/used this on later Mono versions (4.x+) and matching MonoDevelop/Xamarin Studio versions (5.x+) so there might be project attributes/elements that not supported in older versions.... If that is the case, these are really simple project files that if needed you could re-create them using an older MD really quickly, but load them into MD first, try compiling and look at the logs.

**Comment by wallnutkraken** [comment]
`1) Which version of MonoDevelop do you have installed?`
MonoDevelop 4.0.12
`2) If you load the Solution/Project into MonoDevelop and build it from there do you get the same error?`
Can't try it, I'm trying to compile it on a headless machine

**Comment by sushihangover** [comment]
I never tried `mdtool` on a headless install... normally would just package the `.so`s and CIL assemblies for deployment to a headless install from a desktop Linux version...

I'll have to try `mdtool` on a headless install to see if monodevelop is trying to init some display object even though it is not needed.

**Comment by sushihangover** [comment]
Using `mdtool` on a headless box is an issue... 

I created a static build script (`CI/linux.native.compile.sh`) for the `.so` by grabbing the MD build output... a real hack... but it works on an Ubuntu and ArchLinux headless boxes...so give it a try and let me know and i'll pull it into the master branch.

```
git fetch
git checkout linux-headless-hack
CI/linux.native.compile.sh
```

**Comment by wallnutkraken** [comment]
```
(~/repos/CursesSharp) > CI/linux.native.compile.sh
Failed to execute process 'CI/linux.native.compile.sh'. Reason:
exec: Exec format error
The file 'CI/linux.native.compile.sh' is marked as an executable but could not be run by the operating system.
```

Not sure if the script is at fault, though.

**EDIT:**  It compiles if I add `#!/bin/bash` to the beginning of the file. Here's the output:

```
> CI/linux.native.compile.sh
-rwxr-xr-x 1 gnugat gnugat 142576 Nov 30 18:28 CursesSharp.Native/bin/Debug/libCursesWrapper.so
CursesSharp.Native/bin/Debug/libCursesWrapper.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=13b788f2149f870846b4a0352ff6939ad06ede17, not stripped
```

**Comment by sushihangover** [comment]
Thanks, #12 merged...
