### ISSUE TITLE
autoreconf -i fails

### ISSUE THREAD

**Issue by wallnutkraken** [sushihangover/CursesSharp#4]
In the cursessharp-gui branch

Below is the output

> autoreconf -i
> configure.ac:41: installing './compile'
> configure.ac:35: installing './config.guess'
> configure.ac:35: installing './config.sub'
> configure.ac:37: installing './install-sh'
> configure.ac:37: installing './missing'
> configure.ac:224: error: required file 'CursesWrapper/Makefile.in' not found
> configure.ac:224: error: required file 'AttributeGen/Makefile.in' not found
> configure.ac:231: error: required file 'FireworkDemo/Makefile.in' not found
> configure.ac:231: error: required file 'FireworkDemo/FireworkDemo.in' not found
> configure.ac:231: error: required file 'RainDemo/Makefile.in' not found
> configure.ac:231: error: required file 'RainDemo/RainDemo.in' not found
> configure.ac:231: error: required file 'UnicodeDemo/Makefile.in' not found
> configure.ac:231: error: required file 'UnicodeDemo/UnicodeDemo.in' not found
> configure.ac:231: error: required file 'HelloWorldDemo/Makefile.in' not found
> configure.ac:231: error: required file 'HelloWorldDemo/HelloWorldDemo.in' not found
> Makefile.am:3: error: required directory ./CursesWrapper does not exist
> Makefile.am:3: error: required directory ./AttributeGen does not exist
> Makefile.am:3: error: required directory ./FireworkDemo does not exist
> Makefile.am:3: error: required directory ./RainDemo does not exist
> Makefile.am:3: error: required directory ./UnicodeDemo does not exist
> Makefile.am:3: error: required directory ./HelloWorldDemo does not exist
> autoreconf: automake failed with exit status: 1

**Comment by sushihangover** [comment]
I pulled this library originally from http://curses-sharp.sourceforge.net/index.php?page=linux and there was lots of misc issues with it like this (at least on OS-X, where I am use it mainly). 

I have not used to the cmdline make in a while and adding the demos and re-org'ing the source via the Visual Studio/Xamarin Studio solution/project appears to have broken it even more than it was. :-/

FYI: I'll add it on the ToDo list, I would/will just remove all the automake/configure files and just convert it to use xbuild unless someone whats to fix it for automake. ;-)

Thanks, R

**Comment by sushihangover** [comment]
I have updated the project to allow building via mdtool and xbuild.

#9
#8 
#7 
#6
